version: "3.9"
services:
  debayan-scholarqa-es-01:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx30g
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.watermark.low=30mb
      - cluster.routing.allocation.disk.watermark.high=20mb
      - cluster.routing.allocation.disk.watermark.flood_stage=10mb
      - cluster.info.update.interval=1m
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 2200
    networks:
      - elastic

#  kibana:
#    image: kibana:8.2.2
#    ports:
#      - target: 5601
#        published: 5601
#    depends_on:
#      - elasticsearch
#    networks:
#      - elastic      

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge

