version: '3'

services:
        banerjee_arefa_dblplink_api:
                build:
                        context: ./reranker
                        dockerfile: Dockerfile 
                networks: 
                  - dblplink

        banerjee_arefa_dblplink_streamlit:
                build:
                        context: ./
                        dockerfile: Dockerfile
                environment:
                        - STREAMLIT_SERVER_ENABLECORS=false
                        - STREAMLIT_SERVER_ENABLE_CORS=false
                        - STREAMLIT_SERVER_BASEURLPATH=/dblplink
                        - STREAMLIT_SERVER_BASE_URL_PATH=/dblplink
                ports:
                        - "8502:8501"
                networks: 
                  - dblplink
networks:
        dblplink:
                driver: bridge
          
