version: '3'

services:
        banerjee_scholarqa_api:
                build:
                        context: ./kgqa
                        dockerfile: Dockerfile 
                ports:
                        - "5000:5000"
                network_mode: "host"

        banerjee_scholarqa_streamlit:
                build:
                        context: ./streamlit
                        dockerfile: Dockerfile
                environment:
                        - STREAMLIT_SERVER_ENABLECORS=false
                        - STREAMLIT_SERVER_ENABLE_CORS=false
                        - STREAMLIT_SERVER_BASEURLPATH=/scholarqa
                        - STREAMLIT_SERVER_BASE_URL_PATH=/scholarqa
                ports:
                        - "8501:8501"
                network_mode: "host"

